# Generated by Django 5.2.7 on 2026-05-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuuBut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('noi_dung', models.TextField(verbose_name='Lời nhắn')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
