# Generated by Django 5.2.7 on 2026-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luubut',
            name='hinh_anh',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link hình ảnh'),
        ),
    ]
